name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to digitalocean
        run: doctl registry login --access-token=dop_v1_2d9dd6066f303af3d1bb8ba26ec557184a637c5b74773fd832d010924a5e56ea

      - name: ssh to digitalocean droplet name "lemp-s-1vcpu-1gb-sgp1-01"
        run: doctl compute ssh lemp-s-1vcpu-1gb-sgp1-01

      # Runs a set of commands using the runners shell
      - name: Print hello world!
        run: |
          cd /var/www/html
          echo 'Im here! Hello!' >> hello.txt
