name: Staging Deployment

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_to_digita_ocean:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Deploy!
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 157.230.42.139
          key: ${{ secrets.MAC_MINI_PRIVATE_KEY }}
          username: root

          script: |
            cd /var/www/html
            if [ -d "junrhycrodua-api" ]; then rm -Rf junrhycrodua-api; fi
            mkdir junrhycrodua-api && chmod 700 junrhycrodua-api