name: Staging Deployment

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to digitalocean
        run: |
          doctl registry login
          doctl auth list

      - name: Check current account
        run: whoami

      # Runs a set of commands using the runners shell
      - name: Print hello world!
        run: |
          cd /var/www/html/junrhycrodua-api/
          ls
          cat hello.txt
